### ISSUE TITLE
Move S-164 data to this repo

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-164-Sub-Group#2]
Move S-164 data from https://github.com/iho-ohi/S-101-Test-Datasets to this repo.

**Comment by kusala9** [comment]
agree... Needs discussion, maybe move the finished cells but leave specs and other elements behind. The S-164 data should be the finished products only, ready for inclusion in the TDS release....

**Comment by kusala9** [comment]
a few discussions with a few stakeholders on this. For S-164 we need two things

* a "staging area" where data is stored alongside any catalogues and other artifacts we need. There can potentially be multiple versions and data doesn't have to be in any formally defined structure. Issues with content of datasets and supporting resources can then be dealt with and updates to the staging area made.
* an area where we store the prepared exchange sets used by S-164

This repository defines the area where we store the prepared exchange sets and any issues/discussions surrounding them. Issues with content of datasets can also be raised here and linked to issues raised in the staging area. The IHO repository for the S-101 test datasets should be the staging area only for S-101 test datasets used by S-164. So, we should keep the datasets separate. I believe most of the "S-164" folders are ENC content and of varying provenance so I propose we leave that data in S-101-Test-Datasets (but would recommend changing the name of that folder to avoid confusion).

**Comment by kusala9** [comment]
recommend close this. S-164 repo now contains only staging area for data and exchange sets for S-164. S-101 data is primarily sourced from S-101 test datsets repository.  Recommend we close this one, we can bring in any extra data we require into this repository if needed.
