### ISSUE TITLE
CATALOG.XML has invalid bounding polygon

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-164-Sub-Group#26]
v1.1.0/PowerUp/S100_ROOT/CATALOG.XML
file:/S-101/DATASET_FILES/101AA005X02SE.000
![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/c74c749c-e7a7-45f2-b057-8aa3647790f8)

**Comment by kusala9** [comment]
https://github.com/iho-ohi/S-164-Sub-Group/commit/7db2f992c4f5084b6e0c51fbd59056a74496131e fixes this.

**Comment by DavidGrant-NIWC** [comment]
Confirmed - recommend close.
