### ISSUE TITLE
ExchangeSets/S-100/v1.1.0/PowerUp/S100_ROOT/S-101/DATASET_FILES/101AA004X0000.000 is invalid

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-164-Sub-Group#27]
data/ExchangeSets/S-100/v1.1.0/PowerUp/S100_ROOT/S-101/DATASET_FILES/101AA004X0000.000 has an error which prevents loading. 

Error is not present in GitHub\S-101-Test-Datasets\S-164_1.1\V1\2.1.1 Power Up\S100_ROOT\S-101\DATASET_FILES\101AA004X0000.000

**Comment by kusala9** [comment]
maybe dataset has been refreshed in the S_101 repo. Will check.

**Comment by kusala9** [comment]
the new version of this cell (which has producer code 00AA) loads in the viewer using FC 1.1.0 and PC 1.1.0. this can be closed.
