### ISSUE TITLE
Exchange Set Catalogue - GML objects

### ISSUE THREAD

**Issue by HolgerBothien** [iho-ohi/S-164-Sub-Group#30]
I am not an GML expert but <gml:Curve> seems to be a linear object.
The data coverage is an area, so I would recommend to use <gml:Polygon>
example:
```
<gml:Polygon xmlns:gml="http://www.opengis.net/gml/3.2" gml:id="p6" srsName="urn:ogc:def:crs:EPSG::4326">
              <gml:exterior>
                <gml:LinearRing>
                  <gml:posList>-32.56666664 60.98333333 -32.55234272 60.98333333 -32.55233065 60.98431367 -32.54976294 60.98774950 -32.54323478 60.99250749 -32.54097946 60.99543612 -32.53844008 60.99727453 -32.53833329 60.99740772 -32.53833329 61.00833336 -32.56666664 61.00833336 -32.56666664 60.98333333</gml:posList>
                </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
```

Note that I have put the srsName attribute at the object level and use an mrn notation.

Question: should there be any recommendation in S-100?

**Comment by DavidGrant-NIWC** [comment]
GML permits a ridiculous number of ways of representing a polygon, including the use of curves.

![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/0130080b-1f6b-4e92-98fd-bef6cb252103)

**Comment by HolgerBothien** [comment]
I know, GM_Object_PropertyType allows any kind of object. 
My question is: should we limit it to simplify the implementation.
One way of doing it is not using EX_BoundingPolygontype. We could define an own extension like S100_BoundingPolygonType which can be more restrictive. Another way is documentation but I would prefer the first way.

**Comment by TDYCARHugh** [comment]
Agree that there may be too many options available and profiling to refine the choices would be good.  Keep in mind that we still support sharing of geometries in GML and thus we would want to allow a simple polygon with inline geometry or a polygon which references curves that would also be referenced by other objects in a shared scenario.

**Comment by kusala9** [comment]
This was agreed at S100WG8. The default encoding could be added to S-98 Annex C for information. This issue can be closed.
