### ISSUE TITLE
Coordinates in sample catalog

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-164-Sub-Group#33]
Bounding box longitudes are inconsistent, _westBoundLongitude_ should be less than _eastBoundLongitude_:
```
   <gex:westBoundLongitude>
       <gco:Decimal>10.0</gco:Decimal>
   </gex:westBoundLongitude>
   <gex:eastBoundLongitude>
       <gco:Decimal>9.833333</gco:Decimal>
   </gex:eastBoundLongitude>
```

(I am looking at the exchange catalogue in the DisplayBase example.)

**Comment by kusala9** [comment]
I believe these are all now valid and consistent. Fixed by generating bounding boxes from the datasets themselves.
