### ISSUE TITLE
Maximum and minimum display scales in exchange catalog

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-164-Sub-Group#34]
Maximum and minimum display scale values are inconsistent:

maximumDisplayScale (100000) must be less than minimumDisplayScale (45000)

**Comment by kusala9** [comment]
done - changed in creation script. Not sure what the minDisplayScale should be at this stage (tbd) 
https://github.com/iho-ohi/S-164-Sub-Group/commit/761c3c902285a75c993a2cd6d1b85f30c3066fda
