### ISSUE TITLE
data/ExchangeSets/S-100/DisplayBase/CATALOG.XML S100_ExchangeCatalogue.identifier

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-164-Sub-Group#35]
dateTime: The format for _dateTime_ given in S-100 is yyyy-mm-ddThh:mm:ssZ which, strictly read, does not allow fractional seconds.

```xml
<S100XC:dateTime>2023-08-02T08:44:21.618Z</S100XC:dateTime>
```

Some combination of the following will be needed to check this:

- S-100 clarification
- Additional exchange catalogue schema constraint
- S-100 validation rule

Edit: Removed superfluous hyphen from format.

**Comment by kusala9** [comment]
fixed by d5f185696997c3a635d96e58d3ee3dd9f9264a9d - Clarification and validation needs to be tracked via a separate issue in the relevant repo.
