### ISSUE TITLE
ExchangeSets/S-100/PowerUp/S100_ROOT/CATALOG.XML S100_ExchangeCatalogue

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-164-Sub-Group#36]
S100_ExchangeCatalogue/identifier/identifier/dateTime

```xml
<S100XC:dateTime>2023-06-29T08:03:20.880+01:00</S100XC:dateTime>
```
See #35; also, the catalog file in this exchange set uses the zone offset format which is also not allowed according to a strict reading of S-100 Part 17 S100_ExchangeCatalogueIdentifier.

Same remedy as #35.

**Comment by kusala9** [comment]
has been fixed in DIsplayBase, Will be fixed when this exchange set is  scripted.

**Comment by kusala9** [comment]
now fixed in PowerUp as well. This can be closed.
