### ISSUE TITLE
Chart 1 and appropriate FC and PC

### ISSUE THREAD

**Issue by MikusRL** [iho-ohi/S-164-Sub-Group#45]
As discussed today at the SubWG meeting, this is to support Davids request for the Chart 1 necessity sooner than later when working with S-164 test datasets. I suggest also to include FC and PC (and when available also IC) in the S-164 test dataset Exchange sets and scenarios. This was also mutually agreed at both previous S-101PT meetings, that it would remove the ambiguity in used dataset versions and their correct portrayal for the implementer.

The S-164 v.1.0.0 at the introduction pages in Section 1.9 states that:
...
Exchange sets should contain necessary catalogues to perform tests. 
...
and in Section 1.10. states:
...
This section lists the items required for the execution of Tests specified in this document and how the TDS
should be used. The following items are required:
1. IHO S-98 1.0.0 including an ECDIS Chart 1 and colour differentiation diagrams.
...

**Comment by MikusRL** [comment]
Further I would suggest to join the Idea to add the Chart 1 as the version 1.2 with the implementation test for the FC and PC, as the Cahrt 1 could be then imported with the new v.1.2 FC, which could then test the ECDIS further to be able to show the previously installed v.1.1 test datasets along with the v. 1.2 Chart 1.

Then with time the main Power up datasets and updates could be brought to a 1.2, while to maintain the ability to check the multiple FC alongside in ECDIS the Chart 1 then could be at that point brought to 2.0. 

This way when the new version is approved, the test datasets would not be needed to do them all, but only one test dataset, as the rest of the test datasets then would already had a time to upgrade them to a now previous version over much longer time. Just a suggestion to consider.

**Comment by kusala9** [comment]
I've added an exchange set with an initial set of the Chart 1 band 5 larger scale cells. These have been converted from the S-57 ENC and tidied up (all the NEWOBJ have been replaced by either LandArea or SeaArea/NamedWaterAre

There's plenty still to do with these but you can see the scheming of them and quite a lot of the features have converted ok. Still to do is:
* Sort out where the NEWOBJ labels are and use (probably SeaAreaNamedWaterArea to label the cells as per the S-57 versions
* Where NEWOBJ is used to show specific symbols or patterns we probably have to find equivalent features and encode those (i.e feautres which use the portrayal specified int he S-57 NEWOBJ attributes. 
* Any we can't replicate we'll have to work around some other way. Some of the Chart furniture on the first cell will need work to reproduce. 
* The smaller scale band 4 is nearly ready - I will post that when done.

The whole Chart 1 has been moved west so it sits in the scheming next to the S-57 cells. this was a request so the user can inspect the differences between S-101 and S-57 easily.

These can also be ported to v1.2. to be worked on. Now we have a FC and draft PC need to decide when that would be a good time.

**Comment by kusala9** [comment]
sounds good. There's plenty to edit in them still. I've fixed the DataCoverage issue in MNS and we now have a much easier pipeline to put fixes in. I'm working on 5.2 compatibility next, we have Base, Standard and Other datasets nearly ready for testing, then will move onto these Chart 1 ones. We are also doing a side-by-side compare on them with the S-57 to figure out what might be missing. I'm guessing 5.2 is a higher priority though for portrayal catalogue testing?

**Comment by MikusRL** [comment]
> I've fixed the DataCoverage issue in MNS

It looks that the shift could have been lost with the fix...
![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/72803214/f8ea2649-18c3-4191-bee8-b9609d2491aa)

**Comment by kusala9** [comment]
looks like it. I will take a look this afternoon...

**Comment by DavidGrant-NIWC** [comment]
> I'm guessing 5.2 is a higher priority though for portrayal catalogue testing?

Yes, we don't have any data on the 1.2 FC to support PC development/testing.

**Comment by kusala9** [comment]
Sample data for v1.2 is now in the staging area on this repo in data/Staging/S-101/v1.2 

this is Base, Standard and Other. I will add to those and try to fix any issues as best I can. I have some test versions of Chart1 in v1.2, will upload tomorrow. Suggestions on what needs to go into them much appreciated.

**Comment by kusala9** [comment]
v1.2 Chart 1 cells now in the Chart1Dev exchange set. plenty NavAids and other features with converted codes. featureName testing datasets should be coming soon as well.

**Comment by kusala9** [comment]
now resolved viia new Chart1Feature Feature. Test datsets conforming to v1.5.0 of the FC/PC are in https://github.com/iho-ohi/S-164-Sub-Group/tree/main/data/Staging/S-101/v1.5.0/chart1

**Comment by DavidGrant-NIWC** [comment]
I don't believe the datasets (specifically the `DataCoverage` features) are encoded so that they will display correctly when loaded in the ECDIS. There are overlapping scale ranges.

|MSVS|Result|
|:---:|:---:|
|1:45k|![image](https://github.com/user-attachments/assets/b9227772-e66e-422b-86bb-c2b0cf886bfb)|
|1:90k|![image](https://github.com/user-attachments/assets/7d47956c-98e4-41f2-99ae-ae1770eaf4d2)|
