### ISSUE TITLE
Staging/S-101/v1.2/10100AA_DBASE.000 bridge 114 has invalid attribute `categoryOfBridge`

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-164-Sub-Group#48]
the attribute was renamed in 1.2 to `categoryOfOpeningBridge`

![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/e4d92a05-8f4c-4c49-b27e-9daa745cc75d)

**Comment by kusala9** [comment]
done. reopen if still a problem.
