### ISSUE TITLE
`LateralBuoy` has invalid attribution

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-164-Sub-Group#49]
Lateral buoys have been encoded with three single-valued colour attributes instead of a single colour attribute with an array of three values.

Applies to 101AA005C1Q01.000, 101AA005C1Q02.000, 101AA005C1PRS.000, perhaps others.

![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/8486a044-e3a2-46be-b166-e09660e58b6c)

![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/c6da5db5-5804-4fde-bea5-7b6ddce39b4b)

**Comment by kusala9** [comment]
bug in how the attribute indexes are computed when the cells are re-compiled. It's been changed and a new 101AA005C1QO2.000 rebuilt and added to the exchange set. Can this be tested? If all works please close this one. The other cells can then be rebuilt (some may be built with other fixes too). 

![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/3368156/36de1dbb-6900-469e-a0bd-a2457d69f925)

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/6bc98cc4-326d-4a18-9a53-d9c2e1b1cfea)

**Comment by DavidGrant-NIWC** [comment]
Close once all datasets have been corrected.

**Comment by kusala9** [comment]
remade all the datasets. Should be complete now.
