### ISSUE TITLE
101AA005C1AB1.000 contains invalid feature names

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-164-Sub-Group#50]
![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/f3be13d8-6a4e-438f-b898-560e8a1213d2)

`BuoyLateral` should be `LateralBuoy`
`BuoyIsolatedDanger` should be `IsolatedDangerBuoy`

![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/ee75ccb2-74ce-4367-94ce-1e7108c625a5)

**Comment by kusala9** [comment]
fixed both in latest version.
