### ISSUE TITLE
Please add a `Dolphin` of type Surface to 101AA005C1FOO.000

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-164-Sub-Group#53]
To validate portrayal

**Comment by kusala9** [comment]
https://github.com/iho-ohi/S-164-Sub-Group/commit/b4e5dbdc73b573d7b5a4b3ad747ec7ad66afa7c7 for testing. Should be in the latest build of the Chart1 exchange set.

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/4857a181-0597-4df4-ba94-4fbaef58d95e)
