### ISSUE TITLE
SMIN and SMAX values for v.1.2

### ISSUE THREAD

**Issue by MikusRL** [iho-ohi/S-164-Sub-Group#58]
For test datasets already in v.1.2. it looks like it is also forgotten to swap around the values for SMIN and SMAX as per the Prod Spec v1.2:

![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/72803214/930a9bc3-d9b2-4f40-a130-e4f4f837cbe6)

![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/72803214/9b936287-8b25-4949-9f16-8d6e9aa72fc9)

**Comment by kusala9** [comment]
Can you retest this one. I just pushed a new version of the Chart 1 cells to the Repo. I'll do the others when I fix the other outstanding issues with them.  If this is ok, please close this issue.

**Comment by MikusRL** [comment]
@kusala9 Yes, this is now fixed.
![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/72803214/f63d3418-a882-469d-909a-64ba699e087e)
