### ISSUE TITLE
`RecommendedTrack` must have curve geometry

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-164-Sub-Group#62]
Is this a valid encoding? If so, we need an issue in the PSWG to determine symbolization:

![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/e7508fdb-cf0f-4886-86a2-05b48896b87f)

**Comment by kusala9** [comment]
the conversion from S-57 is accurate. They're "unknown" in the S-57 cell. traffic flow is mandatory in DCEG/FC but could be unknown which is the case here. So I think this is valid and can be passed to PSWG....

**Comment by DavidGrant-NIWC** [comment]
Sorry, this issue is actually the result of associating a surface with the `RecommendedTrack`. The FC only allows curves. I'll update the issue title.

**Comment by kusala9** [comment]
ah yes, I can see it in the validation logs now. I'll sort out a Curve as an alternative.

**Comment by kusala9** [comment]
done. A couple of other validation (against FC) fixes picked up too. Check and close this if it's ok now.

**Comment by DavidGrant-NIWC** [comment]
Looks good, but you should change the DS edition number when the dataset changes :-)

![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/a1a281a5-1812-4319-b55e-726e217f63a8)
