### ISSUE TITLE
Access to ECDIS for testing and screenshots

### ISSUE THREAD

**Issue by kusala9** [iho-ohi/S-164-Sub-Group#7]
suggestions for S-100 viewers rto use to generate screenshots. this is likely to be a long-standing issue as some parts of the required functionality haven't been implemented by all..... Need

* import and display of 8211, GML and HDF5 products
* management and storage of catalogues
* import of exchange sets
* Dual Fuel display and operation
* water level adjustment and user selected safety contour
* ECDIS operations (routing, route checks etc...)

**Comment by kusala9** [comment]
close. not useful - we have some viewers but much functionality is still outstanding.

**Comment by DavidGrant-NIWC** [comment]
> close. not useful - we have some viewers but much functionality is still outstanding.

### NIWC Test bed

|Feature|Full Support|Partial Support|Support planned|Will not be supported|Remarks
|:---:|:---:|:---:|:---:|:---:|:---|
|Dual fuel| | | |✔|Believe KHOA testbed supports
|8211| |✔| | |Will need specific S-401 support at minimum
|GML| |✔| | |Will be extended as test data is made available
|HDF5| |✔| | |Will be extended as test data is made available
|Catalog management|✔| | | |In particular, attempts to demonstrate operation with merged portrayal catalogs
|Exchange sets| |✔| | |May be extended to support Part 15 and additional metadata as test exchange sets are made available
|Water level adjustment| | |✔| |Requires supporting test data (co-located 101, 102 & 104)
|ECDIS operations|✔| | | |Believe functionality is sufficient for demonstrating / testing
|Interoperability| | |✔| |Requires supporting catalogs
