### ISSUE TITLE
X01NE ed2: Check that alternate name is UTF-8 encoded

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-164-Sub-Group#81]
Could also be a bug in our tools or the PC...
![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/c320c52b-2822-4892-a737-9a9cb2352576)

**Comment by DavidGrant-NIWC** [comment]
Likely an encoding issue:
![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/d5fcbc84-5996-4a8d-9192-95f2eef024d1)

**Comment by kusala9** [comment]
it uses 0xF6 which is the UTF-8 code for ö - I copied and pasted the feature to another cell and hex dumped the 8211 encoding (below). Is this right encoding? It looks good to me but we can look at it more if this isn't how it's supposed to be encoded...

![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/3368156/767a22cc-192b-49db-b6f1-3c86f125adc1)

**Comment by kusala9** [comment]
think this is working now. Can you retest.? All attributes including names should be encoded in UTF-8. The other cells will be updated as they are rebuilt.

**Comment by DavidGrant-NIWC** [comment]
# 👍
![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/ce11572b-9f52-497d-9d36-70fbf351eb30)
