### ISSUE TITLE
Symbolized boundaries face outwards

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-164-Sub-Group#83]
A lot of the data shows symbolized boundaries which face outwards rather than inwards. This appears to be caused by the boundaries being oriented CCW rather than CW.

![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/65cb778a-da29-424f-b8e1-b218aab1f2e5)

**Comment by kusala9** [comment]
can probably be fixed by reversing the orientation of the geometry of the features I suspect. I will try this one and then some poor soul can try to debug the rest....

**Comment by kusala9** [comment]
this one should probably live in the S-101-Test-Datasets repository. I've commited all these cells to that repo (and will delete them from here probably after the meeting on Monday) . I'll raise this one in that repo too and we can then close this one. It's confusing having data in both so I will delete from this repo as soon as I've cleared it with Tom.

**Comment by DavidGrant-NIWC** [comment]
Closing this since you opened the issue in the other repo. The one you fixed looks good.
