### ISSUE TITLE
Check feature attribution: 10100AA_NAVHZ.000 disagrees with S-64

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-164-Sub-Group#94]
This `Obstruction` feature doesn't produce an indication:
![image](https://github.com/user-attachments/assets/a376f400-21ec-40f2-9230-9c93538fbabb)

but in S-64 it does:
![image](https://github.com/user-attachments/assets/54836eaf-1a29-44ad-af44-5d929a8f7499)

Check the attribution to ensure it has the proper values.

**Comment by kusala9** [comment]
is this a dup of https://github.com/iho-ohi/S-164-Sub-Group/issues/98 ?

**Comment by DavidGrant-NIWC** [comment]
> is this a dup of #98 ?

Not exactly. At the time this was entered I wasn't sure that the attribution on the S-164 feature was correct, but at this point I believe we have verified that it is. Closing.
