### ISSUE TITLE
10100AA_NAVHZ.000 missing feature

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-164-Sub-Group#95]
The 3rd feature in the leg from WP3 to WP4 is missing.

S-101:
![image](https://github.com/user-attachments/assets/fdbd12dd-6b38-41ce-9b67-2fd60200682b)

S-64:
![image](https://github.com/user-attachments/assets/f796d4cf-dc42-4d50-ab3f-c56c5c8cbf0a)

**Comment by kusala9** [comment]
this a duplicate of Issue 97?
