### ISSUE TITLE
1.4.0 powerup datasets: validation errors

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-164-Sub-Group#96]
### 10100AA_X0000
[NauticalInformation:Information|28].information.text "Gas from a damaged oil or gas  [...] osecution if damage is caused." is invalid. string length must not exceed "300".
[NauticalInformation:Information|29].information.text "Gas from a damaged oil or gas  [...] osecution if damage is caused." is invalid. string length must not exceed "300".
[NauticalInformation:Information|30].information.text "Gas from a damaged oil or gas  [...] osecution if damage is caused." is invalid. string length must not exceed "300".
[NauticalInformation:Information|42].information.text "Production platforms and assoc [...] see Mariner`s Handbook NP 100." is invalid. string length must not exceed "300".
[NauticalInformation:Information|43].information.text "The Deep Water Route (DW) has  [...]  Admiralty sailing Directions." is invalid. string length must not exceed "300".
[NauticalInformation:Information|52].information.text "Gas from a damaged oil or gas  [...] osecution if damage is caused." is invalid. string length must not exceed "300".
[NauticalInformation:Information|56].information.text "Gas from a damaged oil or gas  [...] secution if damaged is caused." is invalid. string length must not exceed "300".
[NauticalInformation:Information|62].information.text "Gas from a damaged oil or gas  [...] osecution if damage is caused." is invalid. string length must not exceed "300".
[NauticalInformation:Information|63].information.text "The Deep Water Route (DW) on t [...]  Admiralty Sailing Directions." is invalid. string length must not exceed "300".
[NauticalInformation:Information|68].information.text "Production platforms and assoc [...] the Mariners Handbook| NP 100." is invalid. string length must not exceed "300".
[NauticalInformation:Information|82].information.text "Production platforms and assoc [...] he Mariner`s Handbook| NP 100." is invalid. string length must not exceed "300".
[NauticalInformation:Information|84].information.text "Production platforms and assoc [...] the Mariner`s Handbook NP 100." is invalid. string length must not exceed "300".
[NauticalInformation:Information|86].information.text "Gas from a damaged oil or gas  [...] osecution if damage is caused." is invalid. string length must not exceed "300".
[NauticalInformation:Information|88].information.text "Gas from a damaged oil or gas  [...] osecution if damage is caused." is invalid. string length must not exceed "300".
[PrecautionaryArea:Feature|1198]: invalid number of information attributes: 0 (expected 1:∞)
[PrecautionaryArea:Feature|1779]: invalid number of information attributes: 0 (expected 1:∞)
[Information|1:Information|1] is unreferenced
[Information|66:Information|66] is unreferenced
[Information|69:Information|69] is unreferenced
[Information|8:Information|8] is unreferenced

### 10100AA_X01NE
[Information|3:Information|3] is unreferenced
[Information|2:Information|2] is unreferenced

### 10100AA_X01NW
[Information|5:Information|5] is unreferenced
[Information|3:Information|3] is unreferenced
[Information|1:Information|1] is unreferenced

### 10100AA_X01SE
No errors

### 10100AA_X01SW
[LightSectored:Feature|379].sectorCharacteristics.valueOfNominalRange invalid attribute count: 2 (expected 0:1)
[LightSectored:Feature|379].sectorCharacteristics.valueOfNominalRange invalid attribute count: 2 (expected 0:1)
[LightSectored:Feature|379].sectorCharacteristics.valueOfNominalRange invalid attribute count: 2 (expected 0:1)
[LightSectored:Feature|379].sectorCharacteristics.valueOfNominalRange invalid attribute count: 2 (expected 0:1)
[LightSectored:Feature|379].sectorCharacteristics.valueOfNominalRange invalid attribute count: 2 (expected 0:1)
[LightSectored:Feature|379].sectorCharacteristics.valueOfNominalRange invalid attribute count: 2 (expected 0:1)
[LightSectored:Feature|379].sectorCharacteristics.valueOfNominalRange invalid attribute count: 2 (expected 0:1)
[LightSectored:Feature|379].sectorCharacteristics.valueOfNominalRange invalid attribute count: 2 (expected 0:1)
[LightSectored:Feature|379].sectorCharacteristics.valueOfNominalRange invalid attribute count: 2 (expected 0:1)
[LightSectored:Feature|379].sectorCharacteristics.valueOfNominalRange invalid attribute count: 2 (expected 0:1)
[Information|13:Information|13] is unreferenced
[Information|12:Information|12] is unreferenced
[Information|1:Information|1] is unreferenced

### 10100AA_X02SE
No errors

**Comment by kusala9** [comment]
think these are fixed now....

**Comment by DavidGrant-NIWC** [comment]
> think these are fixed now....

Confirmed.
